adding a button style
clmntnbrn/rb-uxd-code-library pull request #3
Opened 2017-05-22 16:38 UTC by clmntnbrn

Adding a button style - @sashaward I know you've done some other work so I haven't added the grid and other styles, awaiting your pull request 😉

2017-06-05 20:48 UTC, clmntnbrn commented
@sashaward now we need to learn how to resolve conflicts! Fun times!

2017-06-06 08:19 UTC, sashaward commented
@clmntnbrn oh I love conflicts!

2017-06-06 13:24 UTC, barwick requested changes
Please can you use the same font

2017-06-06 13:24 UTC, Xanndarr commented on css/styles.css
> +  font-family: Arial;
Tsk tsk

2017-06-06 13:29 UTC, sashaward approved these changes
✅

2017-06-06 13:29 UTC, sashaward commented on css/styles.css
> +<<<<<<< HEAD
😱

2017-06-06 13:30 UTC, merged